### ISSUE TITLE
Release 0.12 - Testing required: Fedora 28

### ISSUE THREAD

**Issue by reaperzn** [rackerlabs/auter#176]
This issue has been raised as part of the release process for Version 0.12

Please could auter be fully tested on the OS mentioned in the title of this issue. 

# Notes:
 - Please assign yourself to the issue **ONLY IF** you are actively working on it
 - Please ensure you are testing the code from the **v0.12 branch** of this repo
 - Follow the testing guide from https://github.com/rackerlabs/auter/blob/develop/HACKING.md
 - Any problems should be documented in this issue
 - If there are changes required, after the issue has been validated, a new issue should be raised and linked referenced in this issue

**Comment by LukeHandle** [comment]
NOT FINISHED. Have done manual run.


# INSTALL
**ISSUE** Needed to manually add Docker repo with dnf (yum-utils did not work)
```
[root@fedora28 tests]# sed -i 's/ 6 7/ 7/g' 10-rpmbuild.sh
[root@fedora28 tests]# ./10-rpmbuild.sh
Checking if Docker is installed on your Fedora host
 [ FAIL ] docker-ce not installed on Host
Do you want to install docker-ce?
Do you want to install docker-ce?y
./10-rpmbuild.sh: line 22: yum-config-manager: command not found

[root@fedora28 tests]# yum install yum-utils

[root@fedora28 tests]# ./10-rpmbuild.sh
Checking if Docker is installed on your Fedora host
 [ FAIL ] docker-ce not installed on Host
Do you want to install docker-ce?
Do you want to install docker-ce?y

Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.


adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. http://dummy
Traceback (most recent call last):
  File "/usr/bin/yum-config-manager", line 228, in <module>
    grabber = repo.grabfunc; del repo
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 697, in <lambda>
    grabfunc = property(lambda self: self._getgrabfunc())
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 687, in _getgrabfunc
    self._setupGrab()
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 631, in _setupGrab
    urls = self.urls
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 875, in <lambda>
    urls = property(fget=lambda self: self._geturls(),
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 872, in _geturls
    self._baseurlSetup()
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 838, in _baseurlSetup
    self.check()
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 558, in check
    self.ui_id, repo=self)
yum.Errors.RepoError: Cannot find a valid baseurl for repo: dummy
Last metadata expiration check: 0:42:15 ago on Wed 18 Jul 2018 13:05:30 UTC.

[root@fedora28 tests]# dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
[root@fedora28 tests]# dnf install docker-ce

[root@fedora28 tests]# ./10-rpmbuild.sh
Checking if Docker is installed on your Fedora host
AUTERDIR: /root/auter
AUTERPARENTDIR: /root
VERSION: 0.12
Unable to find image 'centos:7' locally
7: Pulling from library/centos
[...]
Digest: sha256:b67d21dfe609ddacf404589e04631d90a342921e81c40aeaf3391f6717fa5322
Status: Downloaded newer image for centos:7
 [ PASSED ] Created 7 docker image
 [ PASSED ] Installed packages to docker image
 [ PASSED ] Added build user
 [ PASSED ] Created rpmbuild structure
 [ PASSED ] Created source tarball from travis container
 [ PASSED ] Moved sources tarball from /root to /root/auter
 [ PASSED ] Copied /tmp/.rpmmacros to docker container
 [ PASSED ] Copied sources to docker container
 [ PASSED ] Copied spec file to docker container
 [ PASSED ] Copied build script to container
I am root... Handing over to builduser
I am builduser... I am building
 [ PASSED ] Executed /home/builduser/11-container-rpmbuild.sh
 [ PASSED ]  /root/auter/auter-7-0.12-1.el7.noarch.rpm file created in travis container
 [ SUCCESS ] All builds were successfull
Stopping leftover containers
ed53e0336197f823113af157f028edbdca575ccca253fdf124cd34e1fa4d805e

[root@fedora28 tests]# dnf install /root/auter/auter-7-0.12-1.el7.noarch.rpm
Last metadata expiration check: 0:08:55 ago on Wed 18 Jul 2018 13:55:28 UTC.
Dependencies resolved.
======================================================================================================================
 Package                    Arch               Version                                 Repository                Size
======================================================================================================================
Installing:
 auter                      noarch             0.12-1.el7                              @commandline              29 k
Installing dependencies:
 cronie-anacron             x86_64             1.5.1-9.fc28                            fedora                    40 k
 crontabs                   noarch             1.11-16.20150630git.fc28                fedora                    24 k
Installing weak dependencies:
 cronie                     x86_64             1.5.1-9.fc28                            fedora                   105 k

Transaction Summary
======================================================================================================================
Install  4 Packages

Total size: 197 k
Total download size: 168 k
Installed size: 359 k
Is this ok [y/N]: y
```

# Basic Checks
**PASS**
```
[root@fedora28 tests]# auter --status
auter is currently enabled and not running
[root@fedora28 tests]# auter --disable
INFO: auter disabled
[root@fedora28 tests]# auter --status
auter is currently disabled
[root@fedora28 tests]# auter --enable
INFO: auter enabled
[root@fedora28 tests]# auter --status
auter is currently enabled and not running

[root@fedora28 tests]# auter --help

Usage: auter [--enable|--disable|--status] [--prep] [--apply] [--reboot] [--postreboot] [OPTIONS]

Automatic Update Transaction Execution by Rackspace. A wrapper around cron and yum/dnf/apt to manage system updates with the ability to configure automatic reboots and custom scripts.

Actions:
  --enable      Enable auter
  --disable     Disable auter. Also deletes unused pidfile if it exists
  --status      Show whether enabled or disabled
  --prep        Pre-download updates before applying
  --apply       Apply updates, and reboot if AUTOREBOOT=yes
  --reboot      Reboot system including pre/post reboot scripts
  --postreboot  Run post reboot script

Options:
  --config=FILE Specify the full path to an auter config file. Defaults to /etc/auter/auter.conf
  --stdout      Always log to STDOUT, regardless of not having a tty
  --skip-all-scripts
                Skip the executions of all custom scripts (Default in /etc/auter/*.d/)

  --skip-scripts-by-phase=PHASE
                Skip the execution of the custom scripts for the specified phase. You can specify myltiple phases.

                Valid Phases: pre-prep, post-prep, pre-apply, post-apply, pre-reboot, post-reboot.

                Example: --skip-scripts-by-phase="pre-prep,post-apply,pre-reboot"

  --skip-scripts-by-name=SCRIPTNAME
                Skip specific scripts by name. You can specify myltiple phases.

                Example: --skip-scripts-by-name="10-configsnap-pre, 20-startApp.sh"

  --no-wall	If possible, suppress shutdown wall messages in the reboot phase
  -h, --help    Show this help text
  -v, --version Show the version

[root@fedora28 tests]# auter --version
auter 0.12

[root@fedora28 tests]# man auter; echo $?
0
[root@fedora28 tests]# man auter.conf; echo $?
0
[root@fedora28 tests]# man -k auter
auter (1)            - Automatic Update Transaction Execution by Rackspace
auter.conf (8)       - Config file for auter
```

# Manual Run
**PASS**
```
[root@fedora28 tests]# yum downgrade zsh
[...]
Downgrade  1 Package

[root@fedora28 tests]# echo 'logger custom pre prep script ran' > /etc/auter/pre-prep.d/pre_prep_script
[root@fedora28 tests]# echo 'logger custom post prep script ran' > /etc/auter/post-prep.d/post_prep_script
[root@fedora28 tests]# echo 'logger custom pre apply script ran' > /etc/auter/pre-apply.d/pre_apply_script
[root@fedora28 tests]# echo 'logger custom post apply script ran' > /etc/auter/post-apply.d/pre_apply_script
[root@fedora28 tests]# echo 'logger custom pre reboot script ran' > /etc/auter/pre-reboot.d/pre_reboot_script
[root@fedora28 tests]# echo 'logger custom post reboot script ran' > /etc/auter/post-reboot.d/post_reboot_script
[root@fedora28 tests]# chmod +x /etc/auter/*.d/*script

[root@fedora28 tests]# egrep -v "^$|^#" /etc/auter/auter.conf
CONFIGSET="default"
AUTOREBOOT="no"
PACKAGEMANAGEROPTIONS=""
PREDOWNLOADUPDATES="yes"
ONLYINSTALLFROMPREP="no"
MAXDELAY="3600"
PACKAGEMANAGERLOCKWAITTIME="60"
PACKAGEMANAGERLOCKRETRIES="5"
PREPREPSCRIPTDIR="/etc/auter/pre-prep.d"
POSTPREPSCRIPTDIR="/etc/auter/post-prep.d"
PREAPPLYSCRIPTDIR="/etc/auter/pre-apply.d"
POSTAPPLYSCRIPTDIR="/etc/auter/post-apply.d"
PREREBOOTSCRIPTDIR="/etc/auter/pre-reboot.d"
POSTREBOOTSCRIPTDIR="/etc/auter/post-reboot.d"

[root@luke8639-fedora28 ~]# auter --prep
INFO: Running with: /usr/bin/auter --prep
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
INFO: Updates downloaded
INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script

[root@fedora28 tests]# cat /var/lib/auter/last-prep-output-default
[...]
Total size: 2.9 M
DNF will only download packages for the transaction.
Downloading Packages:
[SKIPPED] zsh-5.5.1-1.fc28.x86_64.rpm: Already downloaded
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.

[root@fedora28 tests]# auter --apply
INFO: Running with: /usr/bin/auter --apply
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
INFO: Applying updates
INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
INFO: Updates complete (dnf Transaction ID : 16). You may need to reboot for some updates to take effect
INFO: Auter successfully ran at 2018-07-18T16:09:50+00:00

[root@fedora28 tests]# yum check-update
Last metadata expiration check: 0:05:21 ago on Wed 18 Jul 2018 16:07:51 UTC.
[root@fedora28 tests]#

[root@fedora28 tests]# cat /var/lib/auter/last-apply-output-default
[...]
Total download size: 2.9 M
Downloading Packages:
zsh-5.5.1-1.fc28.x86_64.rpm                      21 MB/s | 2.9 MB     00:00
--------------------------------------------------------------------------------
Total                                            21 MB/s | 2.9 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1
  Upgrading        : zsh-5.5.1-1.fc28.x86_64                                1/2
  Running scriptlet: zsh-5.5.1-1.fc28.x86_64                                1/2
  Running scriptlet: zsh-5.5-1.fc28.x86_64                                  2/2
  Cleanup          : zsh-5.5-1.fc28.x86_64                                  2/2
  Running scriptlet: zsh-5.5-1.fc28.x86_64                                  2/2
  Verifying        : zsh-5.5.1-1.fc28.x86_64                                1/2
  Verifying        : zsh-5.5-1.fc28.x86_64                                  2/2

Upgraded:
  zsh.x86_64 5.5.1-1.fc28

Complete!


[root@fedora28 tests]# auter --reboot
INFO: Running with: /usr/bin/auter --reboot
INFO: Running in an interactive shell, disabling all random sleeps
INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
INFO: Rebooting server
[root@fedora28 tests]# Shared connection to XXXXXXXXX closed.

[root@fedora28 ~]# journalctl | grep "custom "
Jul 18 16:05:59 fedora28 root[5599]: custom pre prep script ran
Jul 18 16:06:04 fedora28 root[5623]: custom post prep script ran
Jul 18 16:09:43 fedora28 root[6419]: custom pre apply script ran
Jul 18 16:09:49 fedora28 root[6735]: custom post apply script ran
Jul 18 16:17:55 fedora28 root[6993]: custom pre reboot script ran
Jul 18 16:25:42 fedora28 root[1264]: custom post reboot script ran
```

**Comment by LukeHandle** [comment]
# Test 3: Updates via cron - default config with `--stdout` option [ PASS ]
### Config settings
1) `egrep -v "^$|^#" /etc/auter/auter.conf`
    ```
    [root@luke8639-fedora28 ~]# egrep -v "^$|^#" /etc/auter/auter.conf
    CONFIGSET="default"
    AUTOREBOOT="no"
    PACKAGEMANAGEROPTIONS=""
    PREDOWNLOADUPDATES="yes"
    ONLYINSTALLFROMPREP="no"
    MAXDELAY="3600"
    PACKAGEMANAGERLOCKWAITTIME="60"
    PACKAGEMANAGERLOCKRETRIES="5"
    PREPREPSCRIPTDIR="/etc/auter/pre-prep.d"
    POSTPREPSCRIPTDIR="/etc/auter/post-prep.d"
    PREAPPLYSCRIPTDIR="/etc/auter/pre-apply.d"
    POSTAPPLYSCRIPTDIR="/etc/auter/post-apply.d"
    PREREBOOTSCRIPTDIR="/etc/auter/pre-reboot.d"
    POSTREBOOTSCRIPTDIR="/etc/auter/post-reboot.d"
    ```
2) Prepare custom scripts: Execute:
    ```
    echo 'logger custom pre prep script ran' > /etc/auter/pre-prep.d/pre_prep_script
    echo 'logger custom post prep script ran' > /etc/auter/post-prep.d/post_prep_script
    echo 'logger custom pre apply script ran' > /etc/auter/pre-apply.d/pre_apply_script
    echo 'logger custom post apply script ran' > /etc/auter/post-apply.d/pre_apply_script
    echo 'logger custom pre reboot script ran' > /etc/auter/pre-reboot.d/pre_reboot_script
    echo 'logger custom post reboot script ran' > /etc/auter/post-reboot.d/post_reboot_script
    chmod +x /etc/auter/*.d/*script
    ```
3) Adjust the MAXDELAY value to avoid extented sleep times
    ```
    [root@luke8639-fedora28 ~]# sed -i 's/MAXDELAY.*$/MAXDELAY="60"/g' /etc/auter/auter.conf
    ```
4) Schedule a cron job for prep to run in 5 minutes and watch the logs:
    ```
    echo "$(date --date="5 minutes" +%_M" "%_H" "%d" "%_m" *") root $(which auter) --prep --stdout" > /etc/cron.d/auter-prep
    tail -n0 -f /var/log/messages
    ```
    After auter has completed the prep:
    - __[ pass ]__ Expected logs:
        ```
        auter: INFO: Running with: /usr/bin/auter --prep --stdout
        auter: INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
        root: custom pre prep script ran
        auter: INFO: Updates downloaded
        auter: INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_scrip
        root: custom post prep script ran
        ```
    - __[ pass ]__ **_/var/lib/auter/last-prep-output-default_** contains yum download-only output
    - __[ pass ]__ updates downloaded to **_/var/cache/yum/…_**  <--- `/var/cache/dnf`
    - __[ pass ]__ pre/post prep scripts ran successfully with messages logged to syslog
    - __[ pass ]__ mail sent to root user with stdout output from auter. Debian will log stdout to syslog rather than mail
    Output from logs:
    ```
    Aug 02 12:57:01 luke8639-fedora28 CROND[17381]: (root) CMD (/usr/bin/auter --prep --stdout)
    Aug 02 12:57:01 luke8639-fedora28 CROND[17380]: (root) CMDOUT (INFO: Running with: /usr/bin/auter --prep --stdout)
    Aug 02 12:57:01 luke8639-fedora28 auter[17388]: INFO: Running with: /usr/bin/auter --prep --stdout
    Aug 02 12:57:01 luke8639-fedora28 CROND[17380]: (root) CMDOUT (INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script)
    Aug 02 12:57:01 luke8639-fedora28 auter[17393]: INFO: Running Pre-Prep script /etc/auter/pre-prep.d/pre_prep_script
    Aug 02 12:57:01 luke8639-fedora28 root[17395]: custom pre prep script ran
    [...]
    Aug 02 12:57:25 luke8639-fedora28 CROND[17380]: (root) CMDOUT (INFO: Updates downloaded)
    Aug 02 12:57:25 luke8639-fedora28 auter[17415]: INFO: Updates downloaded
    Aug 02 12:57:25 luke8639-fedora28 CROND[17380]: (root) CMDOUT (INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script)
    Aug 02 12:57:25 luke8639-fedora28 auter[17427]: INFO: Running Post-Prep script /etc/auter/post-prep.d/post_prep_script
    Aug 02 12:57:25 luke8639-fedora28 root[17429]: custom post prep script ran

    [root@luke8639-fedora28 ~]# tail -n 2 /var/lib/auter/last-prep-output-default
    The downloaded packages were saved in cache until the next successful transaction.
    You can remove cached packages by executing 'dnf clean packages'.
    ```
5) Schedule a cron job for apply to run in 5 minutes and watch the logs:
    ```
    echo "$(date --date="5 minutes" +%_M" "%_H" "%d" "%_m" *") root $(which auter) --apply --stdout" > /etc/cron.d/auter-apply
    tail -n0 -f /var/log/messages
    ```
    After auter has completed the apply:
    - __[ pass ]__ Expected logs:
        ```
        auter: INFO: Running with: /usr/bin/auter --apply --stdout
        auter: INFO: Running Pre-Apply script /etc/auter/pre-apply.d/01-configsnap-pre
        auter: INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
        root: custom pre apply script ran
        auter: INFO: Applying updates
        auter: INFO: Running Post-Apply script /etc/auter/post-apply.d/50-configsnap-post-apply
        auter: INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
        root: custom post apply script ran
        auter: INFO: Updates complete (yum Transaction ID : 86). You may need to reboot for some updates to take effect
        auter: INFO: Auter successfully ran at 2018-07-18T14:59:24+0000
        ```
    - __[ pass ]__ no updates available after running
    - __[ pass ]__ pre/post scripts ran successfully with messages logged to syslog
    - __[ pass ]__ mail sent to root user with stdout output from auter. Debian will log stdout to syslog rather than mail
    Output from logs:
    ```
    Aug 02 17:49:02 luke8639-fedora28 CROND[24377]: (root) CMD (/usr/bin/auter --apply --stdout)
    Aug 02 17:49:02 luke8639-fedora28 CROND[24376]: (root) CMDOUT (INFO: Running with: /usr/bin/auter --apply --stdout)
    Aug 02 17:49:02 luke8639-fedora28 auter[24384]: INFO: Running with: /usr/bin/auter --apply --stdout
    Aug 02 17:49:04 luke8639-fedora28 CROND[24376]: (root) CMDOUT (INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script)
    Aug 02 17:49:04 luke8639-fedora28 auter[24394]: INFO: Running Pre-Apply script /etc/auter/pre-apply.d/pre_apply_script
    Aug 02 17:49:04 luke8639-fedora28 root[24396]: custom pre apply script ran
    Aug 02 17:49:39 luke8639-fedora28 CROND[24376]: (root) CMDOUT (INFO: Applying updates)
    Aug 02 17:49:39 luke8639-fedora28 auter[24411]: INFO: Applying updates
    [...]
    Aug 02 17:52:14 luke8639-fedora28 CROND[24376]: (root) CMDOUT (INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script)
    Aug 02 17:52:14 luke8639-fedora28 auter[5479]: INFO: Running Post-Apply script /etc/auter/post-apply.d/pre_apply_script
    Aug 02 17:52:14 luke8639-fedora28 root[5485]: custom post apply script ran
    Aug 02 17:52:15 luke8639-fedora28 CROND[24376]: (root) CMDOUT (INFO: Updates complete (dnf Transaction ID : 18). You may need to reboot for some updates to take effect)
    Aug 02 17:52:15 luke8639-fedora28 auter[6484]: INFO: Updates complete (dnf Transaction ID : 18). You may need to reboot for some updates to take effect
    Aug 02 17:52:15 luke8639-fedora28 CROND[24376]: (root) CMDOUT (INFO: Auter successfully ran at 2018-08-02T17:52:15+00:00)
    Aug 02 17:52:15 luke8639-fedora28 auter[6493]: INFO: Auter successfully ran at 2018-08-02T17:52:15+00:00
    ```
6) Schedule a cron job to run auter --reboot in 5 minutes and watch the logs:
    ```
    echo "$(date --date="5 minutes" +%_M" "%_H" "%d" "%_m" *") root $(which auter) --reboot --stdout" > /etc/cron.d/auter-reboot
    tail -n0 -f /var/log/messages
    ```
    - __[ pass ]__ Expected logs:
        ```
        INFO: Running with: /usr/bin/auter --reboot --stdout
        INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/98-configsnap-pre-reboot
        INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
        custom pre reboot script ran
        INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
        INFO: Rebooting server
        ```
    - __[ pass ]__ pre-reboot scripts ran successfully
    - __[ pass ]__ Wall message is printed
    - __[ pass ]__ mail sent to root user with stdout output from auter. Debian will log stdout to syslog rather than mail
    - __[ pass ]__ Server reboots
    Output from logs:
    ```
    [root@luke8639-fedora28 packages]# journalctl -n0 -f | grep -Ev 'audit|sshd|unix_chkpwd|xe-daemon'
    -- Logs begin at Wed 2018-07-18 12:55:21 UTC. --

    Broadcast message from root@luke8639-fedora28 (Thu 2018-08-02 19:20:01 UTC):

    auter: System reboot to apply updates
    The system is going down for reboot at Thu 2018-08-02 19:22:01 UTC!

    Aug 02 19:20:01 luke8639-fedora28 crond[1093]: (*system*) RELOAD (/etc/cron.d/auter-reboot)
    Aug 02 19:20:01 luke8639-fedora28 CROND[28145]: (root) CMD (/usr/bin/auter --reboot --stdout)
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Running with: /usr/bin/auter --reboot --stdout)
    Aug 02 19:20:01 luke8639-fedora28 auter[28152]: INFO: Running with: /usr/bin/auter --reboot --stdout
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script)
    Aug 02 19:20:01 luke8639-fedora28 auter[28156]: INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
    Aug 02 19:20:01 luke8639-fedora28 root[28158]: custom pre reboot script ran
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default)
    Aug 02 19:20:01 luke8639-fedora28 auter[28163]: INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Rebooting server)
    Aug 02 19:20:01 luke8639-fedora28 auter[28168]: INFO: Rebooting server
    Aug 02 19:20:01 luke8639-fedora28 systemd-logind[469]: Creating /run/nologin, blocking further logins...


    Broadcast message from root@luke8639-fedora28 (Thu 2018-08-02 19:21:01 UTC):

    auter: System reboot to apply updates
    The system is going down for reboot at Thu 2018-08-02 19:22:01 UTC!


    Broadcast message from root@luke8639-fedora28 (Thu 2018-08-02 19:22:01 UTC):

    auter: System reboot to apply updates
    The system is going down for reboot NOW!

    ```
7) After the server has booted, it may take up to 2 minutes for auter logs to appear. watch the logs:
    ```
    egrep "auter:|custom" /var/log/messages | awk '/auter --reboot/,0'
    ```
    - __[ pass ]__ Expected logs:
        ```
        auter: INFO: Running with: /usr/bin/auter --reboot --stdout
        auter: INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
        root: custom pre reboot script ran
        auter: INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
        auter: INFO: Rebooting server
        auter: INFO: Running with: /usr/bin/auter --postreboot --config /etc/auter/auter.conf
        auter: INFO: Removed post-reboot hook: /etc/cron.d/auter-postreboot-default
        auter: INFO: Running Post-Reboot script /etc/auter/post-reboot.d/post_reboot_script
        root: custom post reboot script ran
        ```
    - __[ pass ]__ post-reboot scripts ran successfully
    - __[ pass ]__  output from auter also mailed to the root user on CentOS, output logged to syslog on Fedora
    Output from logs:
    ```
    [root@luke8639-fedora28 ~]# journalctl -S 2018-08-02 | egrep "auter|custom" | awk '/auter --reboot/,0'
    Aug 02 19:20:01 luke8639-fedora28 CROND[28145]: (root) CMD (/usr/bin/auter --reboot --stdout)
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Running with: /usr/bin/auter --reboot --stdout)
    Aug 02 19:20:01 luke8639-fedora28 auter[28152]: INFO: Running with: /usr/bin/auter --reboot --stdout
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script)
    Aug 02 19:20:01 luke8639-fedora28 auter[28156]: INFO: Running Pre-Reboot script /etc/auter/pre-reboot.d/pre_reboot_script
    Aug 02 19:20:01 luke8639-fedora28 root[28158]: custom pre reboot script ran
    Aug 02 19:20:01 luke8639-fedora28 CROND[28144]: (root) CMDOUT (INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default)
    Aug 02 19:20:01 luke8639-fedora28 auter[28163]: INFO: Adding post-reboot-hook to run scripts under /etc/auter/post-reboot.d to /etc/cron.d/auter-postreboot-default
    Aug 02 19:20:01 luke8639-fedora28 auter[28168]: INFO: Rebooting server
    Aug 02 19:22:01 luke8639-fedora28 systemd-logind[469]: System is rebooting (auter: System reboot to apply updates).
    Aug 02 19:22:48 luke8639-fedora28 CROND[1099]: (root) CMD (/usr/bin/auter --postreboot --config /etc/auter/auter.conf)
    Aug 02 19:22:48 luke8639-fedora28 auter[1106]: INFO: Running with: /usr/bin/auter --postreboot --config /etc/auter/auter.conf
    Aug 02 19:22:48 luke8639-fedora28 auter[1110]: INFO: Removed post-reboot hook: /etc/cron.d/auter-postreboot-default
    Aug 02 19:27:48 luke8639-fedora28 auter[1316]: INFO: Running Post-Reboot script /etc/auter/post-reboot.d/post_reboot_script
    Aug 02 19:27:48 luke8639-fedora28 root[1318]: custom post reboot script ran
    ```
